### ISSUE TITLE
Console will not update from Mod Finder

### ISSUE THREAD

**Issue by Yinepuhotep** [Pathfinder-WOTR-Modding-Community/MewsiferConsole#12]
Mod Finder finds updates, and installs Mewsifer Console Menu, but will not install Mewsifer Console. This is the only mod I've consistently been unable to update. Thought it was Mod Finder, but every other mod updates, while this one does not.

**Comment by Yinepuhotep** [comment]
Found what may be the problem. info.json still says it's 1.1.4, not 1.1.5.

**Comment by WittleWolfie** [comment]
Thanks for reporting, fixed.
